info_tuple=()
t=list(info_tuple)
name=input("Enter your name :")
age=int(input("Enter your age :"))
city=input("Enter your city :")
t.append(name)
t.append(age)
t.append(city)
info_tuple=tuple(t)
print(info_tuple)
